{
 "title": "GPU Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "GPU Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(DCGM_FI_DEV_DEC_UTIL)" }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL",
     "legendFormat": "GPU {{kubernetes_node}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED/(DCGM_FI_DEV_FB_USED+DCGM_FI_DEV_FB_FREE)",
     "legendFormat": "GPU {{kubernetes_node}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Count on Per Host",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count by (kubernetes_node) (DCGM_FI_DEV_DEC_UTIL)",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "W" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE",
     "legendFormat": "GPU {{kubernetes_node}} - {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 14 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP",
     "legendFormat": "GPU {{kubernetes_node}} - {{gpu}}"
    }
   ]
  }
 ]
}